create table authors (
    id bigint generated by default as identity,
    full_name varchar(255) not null unique,
    primary key (id)
);

create table genres (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table books (
    id bigint generated by default as identity,
    title varchar(255) not null,
    author_id bigint references authors (id) on delete cascade,
    primary key (id)
);

create table readers (
    id varchar(64) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    pwd_hash varchar(255) not null unique,
    role varchar(32) not null,
    primary key (id)
);

create table comments (
    id bigint generated by default as identity,
    book_id bigint not null references books (id) on delete cascade,
    reader_id varchar(64) not null references readers (id) on delete cascade ,
    text varchar(255) not null,
    comment_date date not null,
    primary key (id)
);

create table books_genres (
    book_id bigint not null references books(id) on delete cascade,
    genre_id bigint not null references genres(id) on delete cascade,
    primary key (book_id, genre_id)
);